// Code generated by counterfeiter. DO NOT EDIT.
package validatefakes

import (
	io "io"
	sync "sync"

	schema "github.com/williammartin/gomg/schema"
	validate "github.com/williammartin/gomg/validate"
)

type FakeSchemaValidator struct {
	ValidateStub        func(io.Reader, io.Reader) (*schema.Result, error)
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 io.Reader
		arg2 io.Reader
	}
	validateReturns struct {
		result1 *schema.Result
		result2 error
	}
	validateReturnsOnCall map[int]struct {
		result1 *schema.Result
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSchemaValidator) Validate(arg1 io.Reader, arg2 io.Reader) (*schema.Result, error) {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 io.Reader
		arg2 io.Reader
	}{arg1, arg2})
	fake.recordInvocation("Validate", []interface{}{arg1, arg2})
	fake.validateMutex.Unlock()
	if fake.ValidateStub != nil {
		return fake.ValidateStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.validateReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSchemaValidator) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeSchemaValidator) ValidateCalls(stub func(io.Reader, io.Reader) (*schema.Result, error)) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeSchemaValidator) ValidateArgsForCall(i int) (io.Reader, io.Reader) {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSchemaValidator) ValidateReturns(result1 *schema.Result, result2 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 *schema.Result
		result2 error
	}{result1, result2}
}

func (fake *FakeSchemaValidator) ValidateReturnsOnCall(i int, result1 *schema.Result, result2 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 *schema.Result
			result2 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 *schema.Result
		result2 error
	}{result1, result2}
}

func (fake *FakeSchemaValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSchemaValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ validate.SchemaValidator = new(FakeSchemaValidator)
